<style>
body {
    background-color: #9400d3; /* Roxo Claro */
    color: white;
}
</style>
---
title: "SOLARIS Escola Iniciática"
output: html_document
---
::: {style="background-color: #e6e6fa; color: black; padding: 20px; text-align: justify;"}
# Bem-vindo à SOLARIS - Escola Iniciática!


# Página Inicial


Olá, eu sou o Mestre Marcus, com 35 anos de experiência, estudos, pesquisas
e práticas Espirituais, estou mais do que apto para ser o seu GUIA nesta
Jornada de Amor e Desenvolvimento Pessoal, Energético e Espiritual, e ainda,
se este for o seu caso, também à nível Profissional (como Terapeuta).

A SOLARIS é uma escola que promove o desenvolvimento humano e Espiritual por
meio de Vídeo-Aulas, Lives, Cursos, Workshops, Retiros, Reuniões em Grupo e
Individuais, Consultorias, Mentorias, Terapias e Práticas. Na sua maioria,
as Aulas e outras propostas da Escola ocorrem Online, mas, há atividades que
são propostas presencialmente, neste caso para quem vive em Portugal
Continental e na Ilha da Madeira, e quem puder deslocar-se até o local
onde estaremos a realizar as Atividades.


## O Que Você Vai Aprender:

Em nossa Escola, você vai aprender:

-   Os mistérios do Homem, sua psiquê, a origem de suas dores e sofrimentos, através das Aulas de Psicologia Esotérica;

-   Os mistérios do Universo, dos planos extrafísicos, dos mundos espirituais, através das Aulas de Metafísica;

-   Você vai ter a oportunidade de receber conteúdos aprofundados sobre Autoconhecimento, com práticas simples, fáceis, objetivas e diretas ao ponto para aplicar no seu dia a dia;

-   Você vai ter a oportunidade de Desenvolver-se psíquicamente (desenvolvimento extrasensorial), a Mediunidade, trabalhar com Energias, Projeção Astral, Paranormalidade, estabelecer contactos com os seres da Natureza e de outros Planos - Mestres, Guias e Mentores;

-   E, se for este o seu chamado, você poderá ajudar outras pessoas que também estão nesta Jornada de Amor e Desenvolvimento Interior.

## Por Que Participar?

Participe da SOLARIS - Escola Iniciática, aqui você vai receber informações e conhecimentos através de conteúdos exclusivos. Uma vez por semana, será disponibilizado o link de uma Aula nova, para além daquelas que já estão gravadas. São 3 Aulas gravadas adicionadas e mais uma Live (ao vivo) mensalmente. E ainda, se for da sua necessidade, poderá uma vez por mês, combinar comigo uma Reunião em direto - seja por mensagem, áudio ou vídeo-chamada - para tirar dúvidas, para receber orientações personalizadas, de acordo com as suas necessidades e interesses.

Navegue pelas páginas para saber mais sobre nossos **serviços** e **cursos**.
:::
